---
# tasks file for tomrole
- name: installing tomcat7 
  apt: 
   name: tomcat7
   state: present

- name: copy tom config files into node
   template:
    src: template/tomconfig.j2
    dest: etc/default/tomcat7
  notify: restart tomcat7

- name: installing packages into tomcat7
  apt:
   name: "{{item}}"
   state: present
  loop:
    -tomcat7-admin
    - tomcat7-docs
    -tomcat7-examples

- name: copy tom config files into nodes
   template:
    src: template/tomuser.j2
    dest: /etc/tomcat7/tomcat-users.xml
  notify: restart tomcat7